version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - backend
  backend:
    build:
      context: server
      dockerfile: Dockerfile
    volumes:
      - ./server/storage:/usr/src/app/storage

networks:
  default:
    external:
      name: webplatform_suilabs
